<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-26T00:51:08 IST" name="Suite" finished-at="2025-06-26T00:51:16 IST" duration-ms="7983">
    <groups>
    </groups>
    <test started-at="2025-06-26T00:51:08 IST" name="Test" finished-at="2025-06-26T00:51:16 IST" duration-ms="7983">
      <class name="com.indium.uber.qa.tests.BookingRideTest">
        <test-method is-config="true" signature="start()[pri:0, instance:com.indium.uber.qa.tests.BookingRideTest@6150c3ec]" started-at="2025-06-26T00:51:09 IST" name="start" finished-at="2025-06-26T00:51:12 IST" duration-ms="3690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="test1()[pri:0, instance:com.indium.uber.qa.tests.BookingRideTest@6150c3ec]" started-at="2025-06-26T00:51:12 IST" name="test1" finished-at="2025-06-26T00:51:12 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.indium.uber.qa.tests.BookingRideTest@6150c3ec]" started-at="2025-06-26T00:51:12 IST" name="teardown" finished-at="2025-06-26T00:51:12 IST" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="start()[pri:0, instance:com.indium.uber.qa.tests.BookingRideTest@6150c3ec]" started-at="2025-06-26T00:51:12 IST" name="start" finished-at="2025-06-26T00:51:15 IST" duration-ms="2239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="test2()[pri:0, instance:com.indium.uber.qa.tests.BookingRideTest@6150c3ec]" started-at="2025-06-26T00:51:15 IST" name="test2" finished-at="2025-06-26T00:51:15 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.indium.uber.qa.tests.BookingRideTest.test2(BookingRideTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.indium.uber.qa.tests.BookingRideTest@6150c3ec]" started-at="2025-06-26T00:51:16 IST" name="teardown" finished-at="2025-06-26T00:51:16 IST" duration-ms="375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.indium.uber.qa.tests.BookingRideTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
